"""
CRUST — RSA keypair generator.

Run this once to create a 2048-bit RS256 keypair and write the base64-encoded
PEM strings to a .env file that can be consumed by the verification service.

    python generate_keys.py [--output .env]

SECURITY: Never commit the generated .env to source control.  The private key
must only be present on the signing service; gateways only need the public key.
"""

from __future__ import annotations

import argparse
import base64
import os
import sys


def generate_keypair() -> tuple[str, str]:
    """
    Generate a 2048-bit RSA keypair.

    Returns:
        (private_key_pem, public_key_pem) — both as UTF-8 strings.
    """
    try:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import rsa
    except ImportError:
        sys.exit(
            "ERROR: 'cryptography' package not installed.\n"
            "Run: pip install cryptography"
        )

    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
    )

    private_pem: str = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode("utf-8")

    public_pem: str = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode("utf-8")

    return private_pem, public_pem


def write_env(output_path: str, private_pem: str, public_pem: str) -> None:
    """Write base64-encoded PEMs to an .env file."""
    private_b64 = base64.b64encode(private_pem.encode("utf-8")).decode("ascii")
    public_b64  = base64.b64encode(public_pem.encode("utf-8")).decode("ascii")

    env_content = (
        "# CRUST RS256 keypair — generated by generate_keys.py\n"
        "# DO NOT COMMIT THIS FILE\n\n"
        f"CRUST_PRIVATE_KEY_PEM={private_b64}\n"
        f"CRUST_PUBLIC_KEY_PEM={public_b64}\n\n"
        "# Service settings (override as needed)\n"
        "MODEL_VERSION=1.0.0\n"
        "MODEL_PATH=model/crust_model.json\n"
        "THRESHOLD_PASS=0.85\n"
        "THRESHOLD_SOFT=0.60\n"
        "THRESHOLD_HARD=0.40\n"
        "RATE_LIMIT_VERIFY=5/second\n"
        "JWT_TTL_SECONDS=900\n"
        "CHALLENGE_TTL_SECONDS=60\n"
    )

    # Never silently overwrite an existing key file
    if os.path.exists(output_path):
        answer = input(f"'{output_path}' already exists. Overwrite? [y/N] ").strip().lower()
        if answer != "y":
            print("Aborted — existing key file preserved.")
            sys.exit(0)

    with open(output_path, "w") as f:
        f.write(env_content)

    # Restrict permissions: owner read/write only
    os.chmod(output_path, 0o600)

    print(f"Keys written to {output_path!r} (permissions: 600)")
    print("\nPublic key (share with gateways):")
    print(public_pem)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate CRUST RSA keypair")
    parser.add_argument(
        "--output", default=".env",
        help="Destination .env file (default: .env)",
    )
    args = parser.parse_args()

    print("Generating 2048-bit RSA keypair …")
    private_pem, public_pem = generate_keypair()
    write_env(args.output, private_pem, public_pem)


if __name__ == "__main__":
    main()
